# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('APP', 'Appetizers'), ('SAL', 'Salads'), ('PAS', 'Pasta'), ('MEA', 'Meats'), ('OTH', 'Other Entrees'), ('SID', 'Sides'), ('DES', 'Desserts')], default=None, max_length=3)),
                ('ingredients', models.TextField()),
                ('directions', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
